name: cms-ars-5.0-k8s-node-stig-overlay
title: cms-ars-5.0-k8s-node-stig-overlay
maintainer: CMS SAF Team
copyright: 
copyright_email: saf@cms.hhs.gov
license: Apache-2.0
summary: "CMS ARS 5.0 Overlay InSpec Validation Profile for Kubernetes STIG Version 1 Release 1"
version: 1.1.0
inspec_version: ">= 4.0"
supports:
- platform: k8s

depends:
- name: k8s-node-stig-baseline
  url: https://github.com/mitre/k8s-node-stig-baseline/archive/main.tar.gz

  - name: audit_log_retention_days
    description: 'Number of days to retain audit logs locally'
    type: Numeric
    value: 90
    profile: k8s-node-stig-baseline

  - name: system_categorization
    desc: "Selected system baseline based on the environment variable"
    type: String
    value: <%= ENV['BASELINE'].nil? ? 'Moderate (Default)' : ENV['BASELINE'] %>

  - name: overlay_controls
    desc: 'List of inapplicable controls/requirements in ARS 5.0 based on the system categorization'
    type: Array
    <% if ENV['BASELINE'] == 'High-HVA' %>
    value: 
      - "V-242436" # AC-6 (8)  
    <% elsif ENV['BASELINE'] == 'High' %>
    value: 
      - "V-242436" # AC-6 (8)
    <% elsif ENV['BASELINE'] == 'Moderate-HVA' %>
    value: 
      - "V-242436" # AC-6 (8)
    <% elsif ENV['BASELINE'] == 'Moderate' || ENV['BASELINE'].nil? %> # Default
    value: 
      - "V-242436" # AC-6 (8)
      - "V-242434" # SC-3
    <% elsif ENV['BASELINE'] == 'Low-HVA' %>
    value: 
      - "V-242436" # AC-6 (8)
      - "V-242381" # AC-2 (1)
      - "V-242416" # SC-10
      - "V-242418" # SC-23
      - "V-242419" # SC-23
      - "V-242420" # SC-23
      - "V-242421" # SC-23
      - "V-242422" # SC-23
      - "V-242423" # SC-23
      - "V-242424" # SC-23
      - "V-242425" # SC-23
      - "V-242426" # SC-23
      - "V-242427" # SC-23
      - "V-242428" # SC-23
      - "V-242429" # SC-23
      - "V-242430" # SC-23
      - "V-242431" # SC-23
      - "V-242432" # SC-23
      - "V-242433" # SC-23
    <% elsif ENV['BASELINE'] == 'Low' %>
    value: 
      - "V-242436" # AC-6 (8)
      - "V-242376" # AC-17 (2)
      - "V-242377" # AC-17 (2)
      - "V-242378" # AC-17 (2)
      - "V-242379" # AC-17 (2)
      - "V-242380" # AC-17 (2)
      - "V-242381" # AC-2 (1)
      - "V-242416" # SC-10
      - "V-242418" # SC-23
      - "V-242419" # SC-23
      - "V-242420" # SC-23
      - "V-242421" # SC-23
      - "V-242422" # SC-23
      - "V-242423" # SC-23
      - "V-242424" # SC-23
      - "V-242425" # SC-23
      - "V-242426" # SC-23
      - "V-242427" # SC-23
      - "V-242428" # SC-23
      - "V-242429" # SC-23
      - "V-242430" # SC-23
      - "V-242431" # SC-23
      - "V-242432" # SC-23
      - "V-242433" # SC-23
      - "V-242434" # SC-3
      - "V-242439" # SC-8
      - "V-242440" # SC-8
      - "V-242441" # SC-8
      - "V-242468" # AC-17 (2)
    <% end %>